---
version: "3.9"
services:
  rafibot:
    image: mov1s/rafibot:latest
    container_name: rafibot
    depends_on:
      - redis
    networks:
      - rafi-net
    environment:
      - HUBOT_DISCORD_TOKEN={secret}
      - HUBOT_GOOGLE_CSE_KEY={secret}
      - HUBOT_GOOGLE_CSE_ID={secret}
      - HUBOT_WUNDERGROUND_API_KEY={secret}
      - HUBOT_APIXU_KEY={secret}
      - EXPRESS_PORT=8080
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    ports:
      - "8090:8080"
  redis:
    image: redis:7.2.4
    container_name: redis
    command: redis-server --dir /data --save 3600 1
    networks:
      - rafi-net
    restart: unless-stopped
    volumes:
      - ./redis/data:/data

networks:
  rafi-net:
    driver: bridge
